default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: mise exec -- pnpm format:check
        language: unsupported
        pass_filenames: false

      - id: lint
        name: lint
        entry: mise exec -- pnpm lint
        language: unsupported
        pass_filenames: false

      - id: typecheck
        name: typecheck
        entry: mise exec -- pnpm typecheck
        language: unsupported
        pass_filenames: false

      - id: test
        name: test
        entry: mise exec -- pnpm test
        language: unsupported
        pass_filenames: false
        stages: [pre-push]
